### ISSUE TITLE
Connecting to forta: Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by hibryid** [rainshowerLabs/blutgang#36]
**Describe the bug**
Balancer is really fast.
Using in metamask/frame everything seems to be working perfectly fine.

But I have some troubles in project called Forta network.
Forta network aims to scan EVM chains and analyze transactions. It requires really high performance of RPC.

I tried to run Blutgang in docker, second time to compile it with last commits. It starts successfully, but every time i get something like these different errors in my nodes.
```
context deadline exceeded (Client.Timeout exceeded while awaiting headers)

bot context is done - exiting request processing loop

context deadline exceeded\n\t* eth_chainId failed
```

Once again:
1. Running node connected to any other rpc and with my own polygon rpc - everything is OK
2. Only when running with blutgang with any single rpc - Errors happen

I guess, it is not possible as a user to quicly and fully reproduce the error without running in production and staking some tokens to get final scores.
Anyway, it is possible to see some unexpected behavior if running locally.

**To Reproduce**

0. Docker must be installed and running
1. Go to [forta's github](https://github.com/forta-network/forta-node) to install from source or get the already compiled app 
2. First run to init the scanner and generate its wallet:
```
forta init --passphrase Your-test-password-123
```
3. Edit the config of forta located `~/.forta/config.yml` for polygon scanning:
```
chainId: 137

scan:
  jsonRpc:
    # real working rpc 
    url: https://polygon-rpc.com/

   # blutgang with that rpc under it to uncomment and run next time
   # url: http://ip:port
   
trace:
  enabled: false
```
4. Run the scan node:
```
forta run --passphrase Your-test-password-123 --no-check
```

It should start 8 containers, container named "forta-scanner" must be there
All stats can be displayed by running `forta status all`

**Expected behavior**
After command `forta status all | grep json-rpc-performance` I expect to see that:
> ⬤ unknown | forta.container.forta-scanner.service.estimator.json-rpc-performance

in ~5 minutes to become something like this:
> ⬤ info | forta.container.forta-scanner.service.estimator.json-rpc-performance | 0.97

In a normal way it shows performance of rpc in float between 0-1, which does not happen with blutgang and stucks on previous previous step

**Specs:**
 - OS: Ubuntu 22.04
 - Kernel: 5.15.0-86-generic
 - Blutgang version: blutgang 0.2.0 Myrddin (last source code) and docker image

**Blutgang options:**
 - DB mode: HighThroughput
 - DB compression: no
 - Cache capacity: 1000000000
 - MA length: 10, also 20 and 100
 - RPCs used: llamarpc, polygon-rpc, quiknode, my own well working rpcs (together and separately, polygon RPCs)

**Additional context**

**Comment by makemake-kbo** [comment]
could you share the full blutgang config? im specifically interested in the TTL, as it might be too low.

**Comment by hibryid** [comment]
Sure.
Forgot to write about TTL.
Tried upto 30000, that shoud be enough I guessed.
Also tried to run web3-proxy. It worked not that fast but correctly.

<details>
<summary>config.toml</summary>

```toml
# To use the config file, use the -c/--config option pointing to the path of a config file
# Config for blutgang goes here
[blutgang]
# Clear the cache DB on startup
do_clear = false
# Where to bind blutgang to
address = "127.0.0.1:6000"
# Moving average length for the latency
ma_length = 100
# Sort RPCs by latency on startup. Recommended to leave on.
sort_on_startup = true
# Enable health checking
health_check = true
# Acceptable time to wait for a response in ms
ttl = 30000
# How many times to retry a request before giving up
max_retries = 32
# Time between health checks in ms
health_check_ttl = 12000

# Note: the admin namespace contains volatile functions and
# should not be exposed publicly.
[admin]
# Enable the admin namespace
enabled = false
# Address for the admin RPC
address = "127.0.0.1:5715"
# Only allow read-only methods
# Recommended `true` unless you 100% need write methods
readonly = false
# Enable the use of JWT for auth
# Should be on if exposing to the internet
jwt = false
# jwt token
token = ""

# Sled config
# Sled is the database we use for our cache, for more info check their docs
[sled]
# Path to db
db_path = "./blutgang-cache"
# sled mode. Can be HighThroughput/LowSpace
mode = "HighThroughput"
# Cache size in bytes. Doesn't matter too much as you OS should also be caching.
cache_capacity = 1000000000
# Use zstd compression. Reduces size 60-70%,
# and increases CPU and latency by around 10% for db writes and 2% for reads
compression = false
# Print DB profile when dropped. Doesn't do anything for now.
print_profile = false
# Frequency of flushes in ms
flush_every_ms = 24000


[pokt]
url = "https://polygon-pokt.nodies.app" # RPC url
# The maximum ammount of time we can use this rpc in a row.
max_consecutive = 25
# Max ammount of querries per second. Doesn't do anything for now.
max_per_second = 0


[polygon-rpc]
url = "https://polygon-rpc.com" # RPC url
# The maximum ammount of time we can use this rpc in a row.
max_consecutive = 25
# Max ammount of querries per second. Doesn't do anything for now.
max_per_second = 0


[polygon-llamarpc]
url = "https://polygon.llamarpc.com" # RPC url
# The maximum ammount of time we can use this rpc in a row.
max_consecutive = 25
# Max ammount of querries per second. Doesn't do anything for now.
max_per_second = 0


[publicnode]
url = "https://polygon-bor.publicnode.com" # RPC url
# The maximum ammount of time we can use this rpc in a row.
max_consecutive = 25
# Max ammount of querries per second. Doesn't do anything for now.
max_per_second = 0


[ankr]
url = "https://rpc.ankr.com/polygon" # RPC url
# The maximum ammount of time we can use this rpc in a row.
max_consecutive = 25
# Max ammount of querries per second. Doesn't do anything for now.
max_per_second = 0

```

</details>
