### ISSUE TITLE
[META] Blutgang 0.3.0 Garreg Mach

### ISSUE THREAD

**Issue by makemake-kbo** [rainshowerLabs/blutgang#57]
This is a meta issue for general questions and troubleshooting related to Blutgang 0.3.0 Garreg Mach.

If you have trouble updating, using, getting undefined behaviour, or anything minor that does not deserve it's own issue, you can report it here.

**Comment by chris-vest** [comment]
@makemake-kbo Trying to run this on Kubernetes, and after checking the RPC latencies, it simply exits:

```
outbound-blutgang-lb-dev-f382c-1 outbound-blutgang-lb Wrn: All data cleared from the database.
outbound-blutgang-lb-dev-f382c-1 outbound-blutgang-lb Info: Starting Blutgang 0.3.0 Garreg Mach
outbound-blutgang-lb-dev-f382c-1 outbound-blutgang-lb Info: Bound to: 0.0.0.0:3000
outbound-blutgang-lb-dev-f382c-1 outbound-blutgang-lb Wrn: Reorg detected!
outbound-blutgang-lb-dev-f382c-1 outbound-blutgang-lb Removing stale entries from the cache.
outbound-blutgang-lb-dev-f382c-1 outbound-blutgang-lb Info: Adding user 1 to sink map
outbound-blutgang-lb-dev-f382c-1 outbound-blutgang-lb Info: Subscribe_user finding: ["newHeads"]
- outbound-blutgang-lb-dev-f382c-1 › outbound-blutgang-lb
```

Running locally with the same config using Docker, it seems to work fine. I have no liveness / readiness set on Kubernetes, so it's not being killed by the orchestrator. 

```
    Last State:     Terminated
      Reason:       Error
      Exit Code:    132
      Started:      Wed, 21 Feb 2024 11:20:37 +0100
      Finished:     Wed, 21 Feb 2024 11:20:49 +0100
```

```
spec:
  containers:
  - args:
    - -c
    - /app/config.toml
    command:
    - /app/blutgang
```

**Comment by makemake-kbo** [comment]
@chris-vest its probably being killed by something. exiting on its own without any error code should not be happening.

**Comment by chris-vest** [comment]
@makemake-kbo Can you confirm the health check endpoint? I saw there was a feature added for it but I can't find the endpoint.

**Comment by chris-vest** [comment]
@makemake-kbo Thank you.

I don't think K8s is killing the container, it seems to error out: 

```
    lastState:
      terminated:
        containerID: containerd://46bd3f545980b859a4be7dfa96463197fbbd8efff6ee1b407167230a86da3957
        exitCode: 132
        finishedAt: "2024-02-21T10:59:28Z"
        reason: Error
        startedAt: "2024-02-21T10:59:28Z"
```
